### ISSUE TITLE
cognitoUser.authenticateUser needs a newPasswordRequired callback

### ISSUE THREAD

**Issue by forrest-akin** [AnomalyInnovations/aws-api-gateway-cli-test#3]
If the cognito user being authenticated is signing in for the first time, they might need to set a new password as well as any other required attributes. I don't think there's a way of pausing execution to accept more args with yargs (maybe with [Vorpal](http://vorpal.js.org/)), but here's the function signature for newPasswordRequired to be added to the callback object in `cognitoUser.authenticateUser(authenticationDetails, callbacks)`

```javascript
newPasswordRequired: function (userAttributes, requiredAttributes) {
  // User was signed up by an admin and must provide new
  // password and required attributes, if any, to complete
  // authentication.

  // userAttributes: object, which is the user's current profile. It will list all attributes that are associated with the user.
  // Required attributes according to schema, which don’t have any values yet, will have blank values.
  // requiredAttributes: list of attributes that must be set by the user along with new password to complete the sign-in.

  // Get these details and call
  // newPassword: password that user has given
  // attributesData: object with key as attribute name and value that the user has given.
  cognitoUser.completeNewPasswordChallenge({NEW_PASSWORD}, {REQUIRED_ATTRIBUTES}, this)
}

**Comment by forrest-akin** [comment]
Agreed. For people following the guide step-by-step, it isn't required. I needed it because I was using bits and pieces of the guide to fill in the gaps of my own project. A helpful error message should suffice!

**Comment by jayair** [comment]
Makes sense. Just updated it.

**Comment by forrest-akin** [comment]
Looks good, thanks!
